language: python
python:
    - "3.4"
install:
    - pip install -r src/requirements_dev.txt
before_script:
    - cd src
script:
    - flake8 c3nav
    - isort -c -rc .
    - python manage.py collectstatic --noinput
    - python manage.py compress
